# Generated by Django 5.2.5 on 2025-08-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='prep_to_min',
        ),
        migrations.AddField(
            model_name='food',
            name='prep_to_min',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
